### ISSUE TITLE
XML source errors...

### ISSUE THREAD

**Issue by lionsdwarf** [qodesmith/thundercats#10]
@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

A user wants immediate playback of sounds on click

This requires low latency which involves populating a sound buffer via XMLHttp request to sound byte urls, the files for which are then decoded and added to the buffer. To do so I am using the AudioSampleLoader.js file linked via the MDN docs for Web Audio Api. 

While there could be some sort of decoding issue, I believe the loader is not accessing the source urls properly. If I hard code a source url, I get a CORS error.

``` js
localhost/:1 XMLHttpRequest cannot load http://www.lettersnstuff.com/sounds/animals/mule.wav. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
audioSampleLoader.js:108 AudioSampleLoader: XMLHttpRequest called onerror
```

 Otherwise, running thru our db, the url points to a single JSON object in the db, not the url specifically and I get this error:

``` js
AudioSampleLoader: ctx.decodeAudioData() called onerroraudioSampleLoader.js:101 (anonymous function)
```

Here's the code from the audioSampleLoader:

``` js
AudioSampleLoader.prototype.loadOneBuffer = function (url) {
  "use strict";
  var console = window.console,
    loader = this,
    XHR = new XMLHttpRequest();
  XHR.open('GET', url, true);
  XHR.responseType = 'arraybuffer';

  XHR.onload = function () {
    loader.ctx.decodeAudioData(
      XHR.response,
      function (buffer) {
        loader.response = buffer;
        loader.onload();
      },
      function () {
        console.error('AudioSampleLoader: ctx.decodeAudioData() called onerror');
        loader.onerror();
      }
    );
  };

  XHR.onerror = function () {
    console.error('AudioSampleLoader: XMLHttpRequest called onerror');
    loader.onerror();
  };
  XHR.send();
};
```

And here's my code that runs the loader and defines the source:

``` js
button.onclick = function() {
  var audioCtx = new (window.AudioContext || window .webkitAudioContext)();
    //Audio Sample Loader is a library that helps   load and decode one or more audio samples.  Functions asynchronously.
    var loader = new AudioSampleLoader();
    //Connects the loader to it's audio context
    loader.ctx = audioCtx;
    //FIXME -- the url is currently directed to a single sound file for testing purposes
    loader.src = 'sounds/1';
    //After a successful decode, the data is  availacle at loader.response as, in our case, an   array of AudioBuffers
    loader.onload = function() {
      window.soundsArray = loader.response;
      console.log('ASL onload complete:');
    };
    //Error msg upon failure
    loader.onerror = function() {
      console.log('Decode failed.');
    };
    //Activates the ASL
    loader.send();
    return loader.response;
  };
```

I've debugged to confirm that my source attr is not retrieving the url properly, however the request is hitting the server.
I've also researched the proper setup for the source url and the most common setup appears that the audio file exists within host server, whereas I'm trying to route some else's .wav file through my server in order to avoid CORS errors. Must I host the audio on our server directly? If not, how must I direct the source?

Please halp!

A frustrated learner.

**Comment by harimohanraj89** [comment]
``` js
    //Activates the ASL
    loader.send();
    return loader.response;
  };
```

After you call `loader.send()`, you're expecting the response to be ready before the next line of code `return loader.response` is executed, but this is not the case. This may be involved in the problem.
