### ISSUE TITLE
hacky use of setTimeout

### ISSUE THREAD

**Issue by lionsdwarf** [qodesmith/thundercats#22]
@harimohanraj89 @DrRobotmck @bigtone1284 @WilliamfShaw 

I used setTimeout to solve a timing problem but this is a hacky solution and has significant drawbacks.

I am using the web audio api in conjunction with backbone model views. As currently configured, my audio buffer loader source is urls populated to the dom via a handlebars template. But those templates aren't executed and the model views don't contain the url info at onload, when my audioLoader function triggers. Consequently, at onload the buffer loader is looking for url's that don't yet exist. So I hacked this with setTimeout, which kinda sorta solves the problem, but kinda sorta doesn't. 

One fear is that if, for some reason, the model view was delayed beyond 1000ms(my current setTimeout interval), then my buffer loader would fail. 

Additionally, there is a separate issue pertaining to the fact that our page contains selectors to repopulate the page/templates with different urls, and in this case having the buffer loader tied to page onload leaves the loader blind to url repopulations. 

One potential solution to the first problem, would be to direct the buffer loader directly to the source in the database, instead of to a value populated by a template.  But this wouldn't necessarily solve the second problem.

Ideally my function to loadAudio would listen to my backbone model views, and reload anytime the views are reset. Is there a way to do this? My code is below and the setTimeout function is at the end. 

``` js
var context = new AudioContext();

var loadAudio = function(pad, url) {
  console.log(pad);
  var request = new XMLHttpRequest();
  request.open('GET', url, true);
  request.responseType = 'arraybuffer';
  request.onload = function() {
    context.decodeAudioData(request.response, function(buffer) { 
      pad.buffer = buffer;
    });
  }
  request.send();
}

var addAudioProperties = function(pad) {
  console.log(pad);
  pad.name = pad.id;
  pad.source = $(pad).data('sound');

  loadAudio(pad, pad.source);
  pad.play = function() {
    var source = context.createBufferSource();
    source.buffer = pad.buffer;
    source.connect(context.destination);
    source.start(0);
    pad.source = source;
  }
}

$(function() {
  setTimeout(function() {
    $('#test div').each(function() {
      addAudioProperties(this);
    });
    $('#test div').click(function() {
      this.play();
    });
  }, 1000);
});
```

**Comment by lionsdwarf** [comment]
@harimohanraj89 

Hari! It's finally working! Maybe for the sake of productivity, it would have made sense to abandon the audio api. But the functionality is awesome and we can really take the sexiness up a level now. Thank you for leading me out of the tunnel (vision). For me, understanding it's incorporation really emphasizes the power and flexibility of Backbone.

**Comment by harimohanraj89** [comment]
Close this issue if it has been resolved.
