### ISSUE TITLE
Cannot run localhost:3000 since heroku change

### ISSUE THREAD

**Issue by qodesmith** [qodesmith/thundercats#24]
When running 'nodemon server.js', I'm getting the error: 
/Users/QuestTheWordsmith/thundercats/models/index.js:10
if (process.env.HEROKU_POSTGRESQL_[GREEN]_URL) {
                                                                                    ^^^^

It doesn't like what was done to models/index.js

**Comment by harimohanraj89** [comment]
You have hard brackets in this file. That looks like a syntax error. How would you fix this?

**Comment by harimohanraj89** [comment]
Make sure to mention all of us on your issues. Otherwise we will **not** see your issue in our notifications.

@harimohanraj89 @DrRobotmck @bigtone1284 @WilliamfShaw
